version: "3.10"

services:
  registry:
    image: registry.localhostaddr.biz.id/registry:2
    #image: registry:2
    networks:
      - net
    ports:
      # Port Registry API
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      # Pastikan folder ini sudah kamu buat di homelab-2
      - /mnt/disk1/registry/data:/var/lib/registry
    deploy:
      placement:
        constraints:
          - node.hostname == homelab-1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Tentukan domain untuk push/pull
        - "traefik.http.routers.registry.rule=Host(`registry.localhostaddr.biz.id`)"
        - "traefik.http.routers.registry.entrypoints=web" # Sesuaikan dengan nama entrypoint HTTP di Traefikmu
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        # Wajib di Swarm jika container menggunakan nama network eksternal
        - "traefik.docker.network=net"

  registry-ui:
    # Gunakan tag main untuk versi V2 yang sudah ada Nginx proxy-nya
    image: registry.localhostaddr.biz.id/joxit/docker-registry-ui:main
    #image: joxit/docker-registry-ui:main
    networks:
      - net
    ports:
      # Port Web Dashboard
      - target: 80
        published: 8080
        protocol: tcp
        mode: ingress
    environment:
      # Konfigurasi spesifik untuk V2
      - SINGLE_REGISTRY=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=Homelab Private Registry
    deploy:
      placement:
        constraints:
          - node.hostname == homelab-1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Tentukan domain untuk mengakses Dashboard Web
        - "traefik.http.routers.registry-ui.rule=Host(`registry-ui.localhostaddr.biz.id`)"
        - "traefik.http.routers.registry-ui.entrypoints=web"
        - "traefik.http.services.registry-ui.loadbalancer.server.port=80"
        - "traefik.docker.network=net"

networks:
  net:
    external: true
