version: "3.10"
services:
  carok-ai:
    image: ghcr.io/decolua/9router:latest
    networks:
      - net
    env_file:
      - .env
    ports:
      # Port Web Dashboard & API (Akses langsung ke Node homelab-1)
      - target: 20128
        published: 20128
        protocol: tcp
        mode: host
    volumes:
      - /mnt/disk1/9router/data:/app/data
    deploy:
      placement:
        constraints:
          - node.hostname == homelab-1

networks:
  net:
    external: true
