version: '3.8'

services:
  alert-service:
    # image: local-alert-service:0.2
    image: registry.localhostaddr.biz.id/alert-service:0.4
    environment:
      - API_KEY=${API_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TZ=Asia/Jakarta
    env_file:
      - .env
    networks:
      - net
    ports:
      - target: 3001
        published: 3001
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  api-manager:
    # image: local-api-manager:0.6
    image: registry.localhostaddr.biz.id/api-manager:0.8
    environment:
      - API_KEY=${API_KEY}
      - STOP_COMMAND=docker service rm homelab_tailscale
      - SAMBA_STOP_COMMAND=docker service rm homelab_samba
      - HOUSEKEEPING_CMD=find /housekeeping -type f -name "*.log" -delete
      - TZ=Asia/Jakarta
      - ALERT_SERVICE_URL=http://alert-service:3001/api/alert
    env_file:
      - .env
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/homelab-infrastructure/docker/tailscale:/data:ro
      - /var/log:/housekeeping
      - /root/homelab-infrastructure/state:/state
      - /root/homelab-infrastructure/docker/samba:/samba:ro
      - /root/homelab-infrastructure/docker/forticlient:/forticlient:ro
      - /root/homelab-infrastructure/docker/carokAI:/9router:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # WAJIB di manager node karena butuh docker.sock host
          - node.role == manager

networks:
  net:
    external: true
