[global]
   server string = samba
   idmap config * : range = 3000-7999
   security = user
   
   # --- PROTOKOL & PERFORMA ---
   server min protocol = SMB2
   server max protocol = SMB3_11
   max xmit = 65535
   getwd cache = yes
   case sensitive = no
   
   # Moving these to global to avoid "found in service section" warning
   read raw = yes
   write raw = yes

   # --- OPTIMASI JARINGAN ---
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   use sendfile = yes
   aio read size = 1
   aio write size = 1
   unix extensions = no

   # --- PRINTING (Minimalist) ---
   # Kita biarkan default RPC berjalan untuk menghindari error code 13 / NT_STATUS_INTERNAL_ERROR
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[Data]
   path = /storage
   comment = Shared
   valid users = angger
   browseable = yes
   writable = yes
   read only = no
   force user = root
   force group = root

   # --- OPTIMASI THUMBNAIL & CACHING ---
   strict locking = no
   oplocks = yes
   level2 oplocks = yes
   allocation roundup size = 4096
   fake directory create times = yes
