name: Deploy via Tailscale SSH

on:
  push:
    branches:
      - main

jobs:
  deploy-homelab:
    name: Deploy via SSH to Homelab
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Tailscale on Homelab
        env:
          API_KEY: ${{ secrets.ALERT_API_KEY }} 
          TSL_API_URL: ${{ secrets.TSL_API_URL }}
        run: |
          curl -s -H "x-api-key: $API_KEY" "$TSL_API_URL"
          sleep 30

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.66.0

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Mendaftarkan IP Statis Tailscale ke known_hosts
          ssh-keyscan -H ${{ secrets.HOST_1_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.HOST_2_IP }} >> ~/.ssh/known_hosts

      - name: Execute Pull on Homelab-1
        env:
          ALERT_API_KEY: ${{ secrets.ALERT_API_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.HOST_1_IP }} << EOF
            cd /root/homelab-infrastructure
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            
            curl -s -X POST http://localhost:3001/api/alert \
              -H "x-api-key: \$ALERT_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{"text": "✅ Sinkronisasi CI/CD Github ke Homelab-1 Berhasil!", "type": "INFO"}'
          EOF

      - name: Execute Pull on Homelab-2
        env:
          ALERT_API_KEY: ${{ secrets.ALERT_API_KEY }}
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.HOST_2_IP }} << EOF
            cd /root/homelab-infrastructure
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            
            curl -s -X POST http://localhost:3001/api/alert \
              -H "x-api-key: \$ALERT_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{"text": "✅ Sinkronisasi CI/CD Github ke Homelab-2 Berhasil!", "type": "INFO"}'
          EOF