version: "3.8"

services:
  homeassistant:
    image: "registry.localhostaddr.biz.id/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/disk1/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    # Menggunakan konfigurasi network swarm untuk host mode
    networks:
      - host
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

networks:
  host:
    name: host
    external: true
  net:
    external: true
