version: "3.10"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    networks:
      - net
    volumes:
      - /mnt/disk1/vaultwarden/data:/data
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.hostname == homelab-1
networks:
  net:
    external: true