version: "3.10"

services:
  vaultwarden:
    # image: vaultwarden/server:latest
    image: registry.localhostaddr.biz.id/vaultwarden/server:latest
    networks:
      - net
    volumes:
      - /mnt/disk1/vaultwarden/data:/data
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.hostname == homelab-1

  vaultwarden-backup:
    image: registry.localhostaddr.biz.id/ttionya/vaultwarden-backup:latest
    #entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      # Mount folder data yang sama sebagai sumber baca
      - /mnt/disk1/vaultwarden/data:/data
      - /mnt/disk1/vaultwarden/config:/config
    env_file:
      - .env
    networks:
      - net
    deploy:
      placement:
        constraints:
          - node.hostname == homelab-1

networks:
  net:
    external: true
